a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('O é um alfanúmericoa?', a.isalpha())
print('O é um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('Está em maiúsculo?', a.isupper())
print('Está em minúsculo?', a.islower())
print('Só tem espaço?', a.isspace())
print('Está capitalizada?', a.istitle())
